# only use troubleshooting
# logLevel: debug

settings:
  clusterName: ${CLUSTER_NAME}
  interruptionQueue: ${CLUSTER_NAME}

serviceAccount:
  name: karpenter-irsa-sa
  annotations:
    eks.amazonaws.com/role-arn: ${ROLE_ARN}

