apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1-inflate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example1-inflate
  template:
    metadata:
      labels:
        app: example1-inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: 1
