apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-17-teama-typeb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example-17-teama-typeb
  template:
    metadata:
      labels:
        app: example-17-teama-typeb
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: team
                operator: In
                values:
                - a
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: example-17-teama-typeb
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: example-17-teama-typeb
      tolerations:
      - key: team
        operator: Equal
        value: a
        effect: NoSchedule
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: "2"
