apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-16-inflate
spec:
  replicas: 6
  selector:
    matchLabels:
      app: example-16-inflate
  template:
    metadata:
      labels:
        app: example-16-inflate
    spec:
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: example-16-inflate
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: example-17-teama-typea-ondemand
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
        resources:
          requests:
            cpu: "1"


