apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: example6-instance-capacitytype
spec:
  template:
    spec:
      requirements:
      # here
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand", "spot"]
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["t"]
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: Gt
        values: ["1"]
      - key: "karpenter.k8s.aws/instance-generation"
        operator: Gt
        values: ["2"]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: example6-instance-capacitytype
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: example6-instance-capacitytype
spec:
  amiFamily: AL2
  # Managed-nodegroup에 설정된 EC2 인스턴스 IAM role을 확인
  role: "eks-from-terraform-eks-worker-node-role"

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "eks-from-terraform"

  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: "eks-from-terraform"
      kubernetes.io/cluster/eks-from-terraform: "owned"
