
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: teama-on-demand
spec:
  template:
    metadata:
      labels:
        team: a
        capacity_type: on-demand
        intent: common
    spec:
      taints:
      - key: "team"
        value: "a"
        effect: "NoSchedule"
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
      - key: capacity-spread
        operator: In
        values:
        - "1"
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: teama-on-demand
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: teama-on-demand
spec:
  amiFamily: AL2
  # Managed-nodegroup에 설정된 EC2 인스턴스 IAM role을 확인
  role: "eks-from-terraform-eks-worker-node-role"

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "eks-from-terraform"

  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: "eks-from-terraform"
