# reference: https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#3-create-a-cluster
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ap-northeast-2
  version: "${K8S_VERSION}"
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}

iam:
  withOIDC: true

managedNodeGroups:
- instanceType: t3.medium
  spot: true
  amiFamily: AmazonLinux2
  name: ${CLUSTER_NAME}-ng
  desiredCapacity: 2
  minSize: 2
  maxSize: 2
