apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: on-demand
spec:
  template:
    spec:
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - r5n.large
        - r5.large
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: on-demand
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: on-demand
spec:
  amiFamily: AL2
  # Managed-nodegroup에 설정된 EC2 인스턴스 IAM role을 확인
  role: "eks-from-terraform-eks-worker-node-role"

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "eks-from-terraform"

  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: "eks-from-terraform"
      kubernetes.io/cluster/eks-from-terraform: "owned"
