apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-17-teama-typea-spot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-17-teama-typea-spot
  template:
    metadata:
      labels:
        app: example-17-teama-typea-spot
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: team
                operator: In
                values:
                - a
              - key: capacity_type
                operator: In
                values:
                - spot
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: capacity-spread
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: example-17-teama-typea-spot
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: example-17-teama-typea-spot
      tolerations:
      - key: team
        operator: Equal
        value: a
        effect: NoSchedule
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: "4"
