apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-provisioner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/choisungwook/karpenter.git
    targetRevision: main
    path: karpenter_provisioner/example-2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
