apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: example8-spot
spec:
  template:
    spec:
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot"]
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["t"]
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values: [nano, micro, small, medium]
      - key: capacity-spread
        operator: In
        values:
        - "2"
        - "3"
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: example8
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: example8-ondemand
spec:
  template:
    spec:
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["t"]
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values: [nano, micro, small, medium]
      - key: capacity-spread
        operator: In
        values:
        - "1"
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: example8
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: example8
spec:
  amiFamily: AL2
  # Managed-nodegroup에 설정된 EC2 인스턴스 IAM role을 확인
  role: "eks-from-terraform-eks-worker-node-role"

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "eks-from-terraform"

  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: "eks-from-terraform"
      kubernetes.io/cluster/eks-from-terraform: "owned"
