apiVersion: apps/v1
kind: Deployment
metadata:
  name: example5-3-no-resources
spec:
  replicas: 100
  selector:
    matchLabels:
      app: example5-3-no-resources
  template:
    metadata:
      labels:
        app: example5-3-no-resources
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
