apiVersion: apps/v1
kind: Deployment
metadata:
  name: example10-inflate
spec:
  replicas: 6
  selector:
    matchLabels:
      app: example10-inflate
  template:
    metadata:
      labels:
        app: example10-inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: "1"
